name: Tag Konflux maintainers for review

on:
  pull_request:
    types:
    - review_requested

permissions:
  contents: read
  pull-requests: write

jobs:
  tag-konflux-maintainers:
    runs-on: ubuntu-latest
    if: |
      github.event.requested_team.name == 'rhtap-maintainers' &&
      github.event.pull_request.user.login == 'msugakov'
    env:
      GH_TOKEN: ${{ secrets.RHACS_BOT_GITHUB_TOKEN }}

    steps:
    - name: Tag Konflux Maintainers for review
      run: |
        set -euo pipefail

        gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/requested_reviewers \
          --input - <<< '{ "team_reviewers": [ "konflux-maintainers" ] }'
